### ISSUE TITLE
Using with Nginx and subdomains

### ISSUE THREAD

**Issue by felix-two-tone** [adamyordan/laplace#1]
Just wondering what kind of config I would need to put this behind nginx. I thought I could just do this

```
server {
    listen 80;

    server_name stream.core0.games;

    return 301 https://stream.core0.games$request_uri;
	
}

 
# HTTPS server
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	server_name stream.core0.games;
    root /*******************/files/;
    main.html;
    charset utf-8;

    # SSL
    ssl_certificate /******fullchain.pem;
    ssl_certificate_key /*******/privkey.pem;


}

```

But when I do and attempt to stream I get a websocket error.

**Comment by felix-two-tone** [comment]
Reading up on it it seems I'll need some config that will bridge the websocket via nginx. 

I have laplace implemented on my server accessible via port number. I guess my issue would be more of a nginx config issue more so then a laplace issue. Feel free to close if you are incline to.

**Comment by adamyordan** [comment]
I tried to put Laplace behind Nginx, and got "Error during WebSocket handshake: Unexpected response code: 502". This looks like a common issue. (https://github.com/websockets/ws/issues/979)

For me, the fix is by setting _proxy_http_version_ and the response headers: _Host_, _Upgrade_, and _Connection_.
```
server {
    server_name  localhost;
    listen       443 ssl;

    ssl_certificate     /etc/nginx/server.crt;
    ssl_certificate_key /etc/nginx/server.key;

    location / {
        proxy_pass https://laplace:443/;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by felix-two-tone** [comment]
Awesome! Yea that did the trick! Thanks for the assist!
